### ISSUE TITLE
Rearrangement of topics when adding them for the first time

### ISSUE THREAD

**Issue by raghavprasad13** [jineetd/discourse-popup#19]
When topics are added for the first time by use of the search bar, the rearrangement works fine. However, the rearrangement order is not reflected in the widget space. This is being caused by the use of various different arrays and sets and whatnot and is leading to a lot of confusion. Instead of doing this, we maintain just one or 2 arrays and the topics can be tracked by the ones present as chips in the form

**Comment by gnowgi** [comment]
Is this happening because the array datatype is not maintained along the way?

**Comment by raghavprasad13** [comment]
@gnowgi Yes. In order to ensure non-duplication of topics in the array, they were converted to sets and then back to arrays before storing them.
It is not a very elegant way to do it. I have thought of a solution to this. Instead of maintaining arrays and sets to keep track of added topics, one can, right before storing them in the DB, merely check the topics that have been added to the form by collecting the HTML elements that appear as "chips" in the form and use that to finally store it in the DB. This will resolve the issue of rearrangement as well.
